[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "apache2", "php82Extensions.pdo", "php82Extensions.pdo_mysql"]

[phases.install]
cmds = ["composer update --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
    "echo 'LoadModule rewrite_module modules/mod_rewrite.so' > /etc/apache2/apache2.conf",
    "echo 'DocumentRoot /app' >> /etc/apache2/apache2.conf",
    "echo '<Directory /app>' >> /etc/apache2/apache2.conf",
    "echo '  AllowOverride All' >> /etc/apache2/apache2.conf",
    "echo '  Require all granted' >> /etc/apache2/apache2.conf",
    "echo '</Directory>' >> /etc/apache2/apache2.conf"
]

[start]
cmd = "apache2 -D FOREGROUND -f /etc/apache2/apache2.conf"